name: packingticketingsystem
description: A Packing Ticket System.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  barcode_scan2: ^4.2.1
  # cached_network_image: ^3.2.2
  # fl_chart: ^0.55.2
  flutter_barcode_scanner: ^2.0.0
  flutter_config: ^2.0.2
  flutter_dotenv: ^5.1.0
  # flutter_launcher_icons: ^0.10.0
  # flutter_polyline_points: ^2.0.0
  # flutter_svg: ^1.1.5
  # font_awesome_flutter: ^10.2.1
  # geolocator: ^9.0.2
  get: ^4.6.6
  google_fonts: ^6.1.0
  # google_maps_flutter: ^2.2.1
  # google_maps_flutter_web: ^0.4.0+3
  # http: ^1.1.0
  # image_picker: ^0.8.4
  # jiffy: ^5.0.0
  # location: ^4.4.0ß
  # otp_text_field: ^1.1.3
  # path_provider: ^2.0.1
  # provider: ^6.0.3
  # qr_code_scanner: ^1.0.1
  # qr_flutter: ^4.0.0
  # shared_preferences: ^2.0.15
  # sqflite: ^2.1.0+1
  supabase_flutter: ^1.10.25
  # timeago: ^3.3.0


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# changed lints to version 3 from "^2.0.0"
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # added the fonts since i got error of failing to fetch google fonts roboto
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/Roboto-Regular.ttf
        # end of addition

  assets:
    - .env
    - assets/images/
