name: packingticketingsystem
description: A Packing Ticket System.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0

  barcode_scan2: ^4.2.1
  flutter_barcode_scanner: ^2.0.0
  flutter_config: ^2.0.2
  flutter_dotenv: ^5.1.0
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  intl_phone_field: ^3.2.0
  flutter_svg: ^2.0.9
  # otp_text_field: ^1.1.3
  # path_provider: ^2.0.1
  # provider: ^6.0.3
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.0.0
  # sqflite: ^2.1.0+1
  supabase_flutter: ^1.10.25
  # timeago: ^3.3.0


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# changed lints to version 3 from "^2.0.0"
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # added the fonts since i got error of failing to fetch google fonts roboto
    

  assets:
    - .env
    - assets/images/
    - assets/icon/

  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans_Regular.ttf
        - asset: assets/fonts/NunitoSans_Light.ttf
          weight: 300
        - asset: assets/fonts/NunitoSans_SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NunitoSans_Bold.ttf
          weight: 700
        - asset: assets/fonts/NunitoSans_ExtraBold.ttf
          weight: 800
    - family: Roboto
      fonts:

